apiVersion: v1
kind: Pod
metadata:
  name: pod-not-running
  labels:
    name: my-testing
spec:
  containers:
  - name: container-not-running
    image: ubuntu
    tty: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
