apiVersion: v1
kind: Pod
metadata:
  name: pod-private
spec:
  containers:
  - name: nginx
    image: fernando93/custom-nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    imagePullSecrets:
      - name: regcred
  