apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: ZmVybmFuZG8K

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    tty: true
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
