apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
  - name: init-container
    image: ubuntu
    tty: true
    volumeMounts:
      - name: init-volume
        mountPath: /var/www
    command: ['touch', '/var/www/index.html']
  containers:
  - name: app-container
    image: ubuntu
    tty: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: init-volume
        mountPath: /var/www
  volumes:
    - name: init-volume
      emptyDir: {}