apiVersion: v1
kind: Pod
metadata:
  name: my-pod-sample-4
  labels:
    env: local
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"